### ISSUE TITLE
Removing metadata corrupts .HEIC files taken from iOS 11 and 12

### ISSUE THREAD

**Issue by cubbage** [Neelfyn/remove-metadata-service#3]
Reproduce:

1. Take picture with standard iPhone XR camera app.
2. Airdrop to Mac.
3. Run the workflow through Quick Actions.
4. Try to open in Preview.

I've attached before and after .HEIC files. 

NOTE: Going to camera settings > Formats > Most Compatible (jpg instead of heic) is a workaround, i.e. .jpgs work ok.
[Before_after.zip](https://github.com/Neelfyn/remove-metadata-service/files/7964772/Before_after.zip)

**Comment by Neelfyn** [comment]
@cubbage Could you try again using [version 0.3](https://github.com/Neelfyn/remove-metadata-service/releases/tag/v0.3)? This should now be fixed.

**Comment by cubbage** [comment]
[Remove Metadata script v0.3 candidate results.zip](https://github.com/Neelfyn/remove-metadata-service/files/9543471/Remove.Metadata.script.v0.3.candidate.results.zip)

So here's a weird thing. 

1. I tried the new version on a random .heic file, and it corrupted it, just like before. So I was going to say "Still doesn't work." But then I noticed the file was an older one from an iPhone 7. 
2. So I tried it on a new photo from my iPhone XR. It worked.
3. So then I tried it on an old iPad Pro 2nd gen photo as well. Also corrupted, like the iPhone 7.

So as far as I can tell, it's fixed on my XR, but not for older photos taken on iPhone 7 and iPad Pro 2nd Gen...

BUT. While it seems like the only difference is the device, I can't be 100% it isn't some other factor, like maybe the photos from my older devices have been through some sort of automated process like being synced and downloaded from Dropbox, or transferred from my old Mac to new, etc. 

Anyway, before and afters are attached as before. This time for all three devices.

**Comment by Neelfyn** [comment]
Having my brief yearly look at this! Haha.

If you happen to be using macOS Ventura, you may have noticed that the _Quick Actions_ menu where Remove Metadata lives now contains a _Convert Image_ menu entry, provided by macOS itself.

On my system, when I use _Convert Image_ on the "BEFORE" pictures from the iPhone 7 and iPad, and select "HEIF" as the output format (with "Actual size" and "Preserve metadata" selected), the conversion takes significantly longer than for newer HEIC files, such as the one from the iPhone XR.

However, after that conversion, _Remove Metadata_ works properly on the newly converted file. Of course, at that point, you may as well simply deselect "Preserve metadata" in the _Convert Image_ Quick Action and achieve the desired result without _Remove Metadata_.

In an up-to-date install of macOS High Sierra, which is the first version of macOS to support HEIF images, I'm also able to circumvent the issue by first opening the iPhone 7 "BEFORE" file in Preview, then exporting it as HEIF again, then running _Remove Metadata_ on the exported file.

If you still have an iPhone 7 or iPad Pro 2nd gen, and it's running the latest available version of iOS, would you be able to take a new picture and see if _Remove Metadata_ still corrupts it as well?

I'm wondering whether these photos were originally encoded in a way that is not currently supported by exiftool, or if the issue was introduced by some other software that modified them. I doubt that a simple sync or transfer would have caused this, but perhaps you've used another photo editing tool on them?

**Comment by Neelfyn** [comment]
On closer inspection, this seems to only affect HEIC photos taken with iOS 11 or 12 specifically, because the color profile is duplicated in the original file, but only written once after metadata is removed.

Corrupted files can be fixed by exporting their color profile and re-importing it as a duplicate:
```
~/Library/Services/Remove\ Metadata.workflow/Contents/Resources/exiftool/exiftool -ICC_Profile -b PATH_TO_IMAGE.HEIC > profile.icc
~/Library/Services/Remove\ Metadata.workflow/Contents/Resources/exiftool/exiftool -P -overwrite_original '-ICC_Profile<=profile.icc' PATH_TO_IMAGE.HEIC
```

Will need to look into whether this can be worked around with exiftool arguments, ideally I would rather not add extra logic to process different kinds of files differently… for now.

**Comment by Neelfyn** [comment]
This issue is now fixed in macOS Sonoma and above, where files previously considered as corrupted (such as those in [this comment](https://github.com/Neelfyn/remove-metadata-service/issues/3#issuecomment-1243043101)) should now open properly.

To work around the issue in older versions of macOS, please either:
* Open photo in Preview and export it as HEIC again, then Remove Metadata
* Convert photo to a different format such as JPEG, then Remove Metadata
* Remove Metadata from HEIC file, then use Terminal commands in [comment above](https://github.com/Neelfyn/remove-metadata-service/issues/3#issuecomment-1846052000) to fix the color profile
